FROM node:12

WORKDIR /app
COPY package.json /app
RUN npm i

ARG NODE_ENV=dev
ENV NODE_ENV=${NODE_ENV}

ARG PG_HOST=localhost
ENV PG_HOST=${PG_HOST}

ARG PG_PORT=5432
ENV PG_PORT=${PG_PORT}

ARG PG_DB=prague-poi
ENV PG_DB=${PG_DB}

ARG PG_USER=prague
ENV PG_USER=${PG_USER}

ARG PG_PASSWORD=p2d2
ENV PG_PASSWORD=${PG_PASSWORD}

WORKDIR /app
COPY . /app
CMD NODE_ENV=${NODE_ENV} \
  PG_HOST=${PG_HOST} PG_PORT=${PG_PORT} PG_DB=${PG_DB} PG_USER=${PG_USER} PG_PASSWORD=${PG_PASSWORD} \
  node main.js
